jquery_lang_js.prototype.lang.tw = {
'accesscontrol.FunctionID':'功能代號*',
'accesscontrol.ModuleName':'模組名*',
'accesscontrol.ModuleDirectory':'模組目錄*',
'accesscontrol.PathToProgramName':'程式名稱*',
'accesscontrol.AccessLevels':'權限*',

'adscontent.CompanyAdsID':'廣告編號*',
'adscontent.CompanyID':'店家代號*',
'adscontent.LanguageID':'語言代號*',
'adscontent.AdsTitle':'標題*',
'adscontent.AdsDesc':'簡介',
'adscontent.NewsCreateTime':'建檔時間',

'allianceuser.AllianceUserID':'聯盟編號*',
'allianceuser.StaffID':'成員編號*',
'allianceuser.ParentNode':'主節點*',
'allianceuser.BonusShare':'紅利分潤*',
'allianceuser.RebaitShare':'外客回饋*',
'allianceuser.CreateTime':'建檔時間*',
'allianceuser.UpdateTime':'修改時間*',
'allianceuser.CreatedBy':'建檔人*',
'allianceuser.UpdateBy':'經手人*',

'announcement.AnnounceID':'活動編號*',
'announcement.UpdateBy':'經手人*',
'announcement.PromoID':'專案編號*',
'announcement.AnnounceTitle':'活動標題',
'announcement.AnnounceDesc':'活動簡介',
'announcement.AnnouncePic':'活動照片',
'announcement.UpdateTime':'修改時間',

'awardredeem.AwardID':'獎賞編號*',
'awardredeem.PromoID':'專案編號*',
'awardredeem.PrizeID':'獎品代號*',
'awardredeem.UserID':'使用者帳號*',
'awardredeem.PrizeCode':'獎品編碼',
'awardredeem.AwardTime':'得獎時間',
'awardredeem.RedeemTime':'領獎時間',
'awardredeem.CounterID':'櫃台編號*',
'awardredeem.RedeemNote':'注意事項',
'awardredeem.Expired':'過期',

'bonusaccount.BonusAccountID':'紅利帳戶*',
'bonusaccount.UserID':'使用者帳號*',
'bonusaccount.TotalAward':'獲得點數',
'bonusaccount.TotalRedeem':'兌換點數',
'bonusaccount.CurrentPoints':'剩餘點數',
'bonusaccount.UpdateTime':'修改時間',
'bonusaccount.UpdateBy':'經手人*',

'bonusgoods.GoodsID':'商品代號*',
'bonusgoods.CompanyID':'店家代號*',
'bonusgoods.GoodsName':'商品名稱*',
'bonusgoods.GoodsDesc':'商品簡介',
'bonusgoods.GoodsPic':'商品照片',
'bonusgoods.GoodsPic2':'商品照片2',
'bonusgoods.GoodsPic3':'商品照片3',
'bonusgoods.GoodsPic4':'商品照片4',
'bonusgoods.GoodsPic5':'商品照片5',
'bonusgoods.GoodsQuantity':'商品數量*',
'bonusgoods.GoodsPrice':'商品價格*',
'bonusgoods.GoodsBonusValue':'商品獎勵價值*',
'bonusgoods.GoodsState':'商品狀態*',
'bonusgoods.StartingDate':'開始日*',
'bonusgoods.ExpiredDate':'過期日*',
'bonusgoods.CreateTime':'建檔時間*',
'bonusgoods.UpdateTime':'修改時間*',
'bonusgoods.UpdateBy':'經手人*',

'bonusrulesetting.BonusRuleSettingID':'紅利規則設定*',
'bonusrulesetting.CompanyID':'店家代號*',
'bonusrulesetting.BounsBase':'紅利基準*',
'bonusrulesetting.BonusValuex100':'紅利價值x100*',
'bonusrulesetting.BonusFee':'獎勵費*',
'bonusrulesetting.UpdateTime':'修改時間*',
'bonusrulesetting.UpdateBy':'經手人*',

'bonustx.BonusTxID':'紅利發送編號*',
'bonustx.CompanyID':'店家代號*',
'bonustx.UserID':'使用者帳號*',
'bonustx.BonusPoints':'紅利點數*',
'bonustx.BonusTxType':'紅利發送方式*',
'bonustx.BonusTxTime':'紅利發送時間*',
'bonustx.DeviceID':'設備編號*',
'bonustx.BonusTxNote':'注意事項*',

'caimaassigment.CaimaAssigmentID':'彩碼分配編號*',
'caimaassigment.CaimaRepositoryID':'彩碼儲存庫編號*',
'caimaassigment.CompanyID':'店家代號*',

'caimabatch.BatchID':'批次編號*',
'caimabatch.BatchName':'批次名稱*',
'caimabatch.BatchDescription':'批次說明',

'caimarepository.caimarepositoryID':'彩碼儲存庫編號*',
'caimarepository.CaimaID':'彩碼編號*',
'caimarepository.BatchID':'批次編號*',
'caimarepository.UsageState':'使用狀態*',
'caimarepository.CompanyCaima90URL':'彩碼位址90URL*',
'caimarepository.CompanyCaima450URL':'彩碼位址450URL*',

'company.CompanyID':'店家代號*',
'company.CompanyAdm':'店家管理者*',
'company.CompanyName':'店名*',
'company.CompanyDesc':'簡介*',
'company.CompanyPic':'照片1*',
'company.CompanyPic2':'照片2',
'company.CompanyPic3':'照片3',
'company.CompanyPic4':'照片4',
'company.CompanyPic5':'照片5',
'company.CompanyOfficialSite':'官網',
'company.ContactPerson':'連絡人',
'company.ContactEmail':'E-mail',
'company.ContactPhone':'連絡電話',
'company.Address':'地址*',
'company.BizRegNo':'郵遞區號',
'company.parkingLot':'停車場',
'company.lowestSpending':'最低消費',
'company.StartingTime':'開始時間',
'company.EndingTime':'結束時間',
'company.Latitude':'緯度*',
'company.Longitude':'經度*',
'company.CreateTime':'建檔時間*',
'company.UpdateTime':'修改時間*',
'company.CreateBy':'建檔人*',
'company.UpdateBy':'經手人*',

'companyads.CompanyAdsID':'廣告編號*',
'companyads.CompanyID':'店家代號*',
'companyads.AdsTitle':'標題*',
'companyads.AdsDesc':'說明*',
'companyads.AdsPic':'照片',
'companyads.AdsCreateTime':'建檔時間',
'companyads.AdsUpdateTime':'修改時間',
'companyads.AdsUpdateBy':'經手人',

'companycontent.companycontentID':'店家編號*',
'companycontent.CompanyID':'店家代號*',
'companycontent.LanguageID':'語言代號*',
'companycontent.CompanyName':'店名',
'companycontent.CompanyDesc':'店家簡介',
'companycontent.Address':'地址',
'companycontent.Modified':'修正',

'companynews.CompanyNewsID':'訊息編號*',
'companynews.CompanyID':'店家代號*',
'companynews.NewsTitle':'標題*',
'companynews.NewsDesc':'說明1*',
'companynews.NewsPic':'照片1',
'companynews.NewsDesc2':'說明2',
'companynews.NewsPic2':'照片2',
'companynews.NewsCreateTime':'建檔時間',
'companynews.NewsUpdateTime':'修改時間',
'companynews.NewsUpdateBy':'經手人',

'companytags.CompanyTagsID':'店家標籤編號*',
'companytags.CompanyID':'店家代號*',
'companytags.TagLists':'標籤列表*',
'companytags.ParentTagID':'主標籤ID',

'companytemp.CompanyID':'店家代號*',
'companytemp.CompanyAdm':'店家管理者*',
'companytemp.CompanyName':'店名*',
'companytemp.CompanyDesc':'店家簡介*',
'companytemp.CompanyPic':'照片',
'companytemp.CompanyOfficialSite':'官網',
'companytemp.ContactPerson':'連絡人',
'companytemp.ContactEmail':'E-mail',
'companytemp.ContactPhone':'連絡電話',
'companytemp.Address':'地址*',
'companytemp.BizRegNo':'統編',
'companytemp.Latitude':'緯度',
'companytemp.Longitude':'經度',
'companytemp.CreateTime':'建檔時間*',
'companytemp.UpdateTime':'修改時間*',
'companytemp.CreateBy':'建檔人*',
'companytemp.UpdateBy':'經手人*',

'customercaima.CustomerCaimatID':'用戶彩碼編號*',
'customercaima.CaimaRepositoryID':'彩碼儲存庫編號*',
'customercaima.UserID':'使用者帳號*',

'customervehicle.CustomerVehicleID':'用戶載具編號*',
'customervehicle.UserID':'使用者帳號*',
'customervehicle.CardID':'卡號*',
'customervehicle.Phone':'電話*',

'fanscompany.promocompanyID':'店家代號*',
'fanscompany.PromoID':'專案編號*',
'fanscompany.CompanyID':'店家代號*',

'goodstx.GoodsTxID':'商品發送編號*',
'goodstx.GoodsID':'商品編號*',
'goodstx.UserID':'使用者帳號*',
'goodstx.GoodsTxState':'商品發送狀態',
'goodstx.ReserveTime':'商品預約時間*',
'goodstx.RedeemTime':'兌換時間*',

'goodstxnotes.GoodsTxID':'商品發送編號*',
'goodstxnotes.Description':'說明*',
'goodstxnotes.CreateTime':'建檔時間*',
'goodstxnotes.UpdateTime':'修改時間*',
'goodstxnotes.UpdateBy':'經手人*',

'group.GroupID':'群組編號*',
'group.CaimaID':'彩碼編號*',
'group.GroupTypeID':'群組類型ID*',
'group.PromoID':'專案編號*',
'group.StarterID':'發起人ID*',
'group.GroupName':'群組名稱*',
'group.GroupDesc':'群組簡介',
'group.StartTime':'開始時間',
'group.DescUpdateTime':'修改時間',
'group.GroupURL':'群組URL',

'grouptype.GroupTypeID':'群組類型ID*',
'grouptype.PromoID':'專案編號*',
'grouptype.GroupTypeName':'群組類型名稱*',
'grouptype.GroupTypeQuote':'群組類型摘要',

'joinfans.JoinID':'註冊編號*',
'joinfans.PromoID':'專案編號*',
'joinfans.UserID':'使用者帳號*',
'joinfans.CompanyID':'店家代號*',
'joinfans.Comment':'評論',
'joinfans.JoinTime':'加入時間',
'joinfans.LeaveTime':'退出時間',

'joingroup.JoinID':'註冊編號*',
'joingroup.PromoID':'專案編號*',
'joingroup.UserID':'使用者帳號*',
'joingroup.GroupID':'群組編號*',
'joingroup.Comment':'評論',
'joingroup.JoinTime':'加入時間',
'joingroup.LeaveTime':'退出時間',

'languagemapping.LanguageID':'語言代號*',
'languagemapping.LanguageName':'語言名稱*',
'languagemapping.languageEncode':'語言編碼',

'offday.offDayID':'休息日ID*',
'offday.name':'休息日名稱*',

'offdaycompany.offDayCompany':'店名*',
'offdaycompany.CompanyID':'店家代號*',
'offdaycompany.offDayID':'休息日ID*',

'paymentmethod.paymentMethodID':'付款方式*',
'paymentmethod.methodName':'付款名稱*',

'pos.PosID':'PosID*',
'pos.PosName':'Pos名稱*',
'pos.Description':'說明',
'pos.PosState':'Pos狀態*',
'pos.CreateTime':'建檔時間*',
'pos.UpdateTime':'修改時間*',
'pos.UpdateBy':'經手人*',

'posnotes.PosNotesID':'Pos注意事項*',
'posnotes.PosID':'PosID*',
'posnotes.Description':'說明*',
'posnotes.CreateTime':'建檔時間',
'posnotes.UpdateTime':'修改時間',
'posnotes.UpdateBy':'經手人*',

'prizeitem.PrizeID':'獎品編號*',
'prizeitem.PromoID':'專案編號*',
'prizeitem.UpdateBy':'經手人*',
'prizeitem.PrizeName':'獎品名稱*',
'prizeitem.PrizeDesc':'獎品說明',
'prizeitem.PrizeQuantity':'獎品數量*',
'prizeitem.AwardMsg':'得獎訊息',
'prizeitem.RedeemMsg':'兌換訊息',
'prizeitem.ExpiredDate':'過期日*',
'prizeitem.ExpiredMsg':'過期訊息',
'prizeitem.CreateTime':'建檔時間*',
'prizeitem.UpdateTime':'修改時間*',

'promotion.PromoID':'專案編號*',
'promotion.CompanyID':'店家代號*',
'promotion.PromoAdmin':'專案管理者*',
'promotion.PromoName':'專案名稱',
'promotion.PromoDesc':'專案簡介',
'promotion.PromoURL':'PromoURL',
'promotion.AndroidURL':'AndroidURL',
'promotion.AppleURL':'AppleURL',
'promotion.StartTime':'開始時間*',
'promotion.EndTime':'結束時間*',
'promotion.BatchID':'批次編號*',

'rebaterulesetting.RebateRuleSettingID':'回饋規則設定ID*',
'rebaterulesetting.CompanyID':'店家代號*',
'rebaterulesetting.RebateBase':'回饋基準*',
'rebaterulesetting.RebateValuex100':'回饋價值x100*',
'rebaterulesetting.RebateFee':'回饋費用*',
'rebaterulesetting.UpdateTime':'修改時間*',
'rebaterulesetting.UpdateBy':'經手人*',

'rebatestorelists.RebateStoreListsID':'回饋商店列表*',
'rebatestorelists.CompanyID':'店家代號*',
'rebatestorelists.PosID':'PosID*',
'rebatestorelists.CreateTime':'建檔時間*',
'rebatestorelists.UpdateTime':'修改時間*',
'rebatestorelists.UpdateBy':'經手人*',

'rebatetx.RebateTxID':'回饋發送ID*',
'rebatetx.CompanyID':'店家代號*',
'rebatetx.PosID':'PosID*',
'rebatetx.UserID':'使用者帳號*',
'rebatetx.RebatePoints':'回饋點數*',
'rebatetx.RebateTxType':'回饋發送類型*',
'rebatetx.RebateTxTime':'回饋發送時間*',
'rebatetx.RebateTxNote':'注意事項*',

'Redeemcounter.CounterID':'櫃台編號*',
'Redeemcounter.PromoID':'專案編號*',
'Redeemcounter.CounterName':'櫃台名稱*',
'Redeemcounter.CountLocation':'櫃台位置*',
'Redeemcounter.AuthCode':'驗證碼*',

'staff.StaffID':'成員編號*',
'staff.Username':'姓名*',
'staff.Valid':'有效*',
'staff.Password':'密碼*',
'staff.GoogleID':'登入帳號*',
'staff.UserLevel':'權限*',
'staff.StaffDesc':'說明',
'staff.Email':'E-mail*',
'staff.Phone':'電話',
'staff.CreateTime':'建檔時間',
'staff.UpdateTime':'修改時間',
'staff.UpdateBy':'經手人',

'stafflevel.UserLevel':'權限*',
'stafflevel.LevelName':'權限名稱*',

'storegroup.StoreGroupID':'店群代號*',
'storegroup.GroupLead':'群首*',
'storegroup.StoreGroupName':'店群名稱*',
'storegroup.SotreGroupDesc':'店群簡介',
'storegroup.StoreGroupURL':'店群網址',
'storegroup.StoreGroupState':'店群狀態',

'storegrouplists.StoreGroupListID':'店群列表*',
'storegrouplists.CompanyID':'店家代號*',
'storegrouplists.StoreGroupID':'店群代號*',
'storegrouplists.AllianceUserID':'聯盟代號*',
'storegrouplists.CreateTime':'建檔時間*',
'storegrouplists.UpdateTime':'修改時間*',
'storegrouplists.UpdateBy':'經手人*',

'tagmapping.TagID':'標籤ID*',
'tagmapping.ParentTagID':'主標籤',
'tagmapping.TagName':'標籤名稱*',
'tagmapping.LanguageID':'語言代號',

'user.UserID':'使用者帳號*',
'user.UserName':'姓名*',
'user.FB_ID':'FB_ID',
'user.FB_profile':'FB_簡述',
'user.RegTime':'註冊時間',
'user.RegPromo':'註冊促銷*',
'user.Valid':'有效',
'user.LanguageID':'語言代號*',

'uservehicle.UserVehicleID':'載具編號*',
'uservehicle.UserID':'使用者帳號*',
'uservehicle.CardID':'卡號',
'uservehicle.Phone':'電話*',
}