jquery_lang_js.prototype.lang.tw = {
'accesscontrol.FunctionID':'FunctionID*',
'accesscontrol.ModuleName':'ModuleName*',
'accesscontrol.ModuleDirectory':'ModuleDirectory*',
'accesscontrol.PathToProgramName':'PathToProgramName*',
'accesscontrol.AccessLevels':'AccessLevels*',

'adscontent.CompanyAdsID':'CompanyAdsID*',
'adscontent.CompanyID':'CompanyID*',
'adscontent.LanguageID':'LanguageID*',
'adscontent.AdsTitle':'AdsTitle*',
'adscontent.AdsDesc':'AdsDesc',
'adscontent.NewsCreateTime':'NewsCreateTime',

'allianceuser.AllianceUserID':'AllianceUserID*',
'allianceuser.StaffID':'StaffID*',
'allianceuser.ParentNode':'ParentNode*',
'allianceuser.BonusShare':'BonusShare*',
'allianceuser.RebaitShare':'RebaitShare*',
'allianceuser.CreateTime':'CreateTime*',
'allianceuser.UpdateTime':'UpdateTime*',
'allianceuser.CreatedBy':'CreatedBy*',
'allianceuser.UpdateBy':'UpdateBy*',

'announcement.AnnounceID':'AnnounceID*',
'announcement.UpdateBy':'UpdateBy*',
'announcement.PromoID':'PromoID*',
'announcement.AnnounceTitle':'AnnounceTitle',
'announcement.AnnounceDesc':'AnnounceDesc',
'announcement.AnnouncePic':'AnnouncePic',
'announcement.UpdateTime':'UpdateTime',

'awardredeem.AwardID':'AwardID*',
'awardredeem.PromoID':'PromoID*',
'awardredeem.PrizeID':'PrizeID*',
'awardredeem.UserID':'UserID*',
'awardredeem.PrizeCode':'PrizeCode',
'awardredeem.AwardTime':'AwardTime',
'awardredeem.RedeemTime':'RedeemTime',
'awardredeem.CounterID':'CounterID*',
'awardredeem.RedeemNote':'RedeemNote',
'awardredeem.Expired':'Expired',

'bonusaccount.BonusAccountID':'BonusAccountID*',
'bonusaccount.UserID':'UserID*',
'bonusaccount.TotalAward':'TotalAward',
'bonusaccount.TotalRedeem':'TotalRedeem',
'bonusaccount.CurrentPoints':'CurrentPoints',
'bonusaccount.UpdateTime':'UpdateTime',
'bonusaccount.UpdateBy':'UpdateBy*',

'bonusgoods.GoodsID':'GoodsID*',
'bonusgoods.CompanyID':'CompanyID*',
'bonusgoods.GoodsName':'GoodsName*',
'bonusgoods.GoodsDesc':'GoodsDesc',
'bonusgoods.GoodsPic':'GoodsPic',
'bonusgoods.GoodsQuantity':'GoodsQuantity*',
'bonusgoods.GoodsPrice':'GoodsPrice*',
'bonusgoods.GoodsBonusValue':'GoodsBonusValue*',
'bonusgoods.GoodsState':'GoodsState*',
'bonusgoods.ExpiredDate':'ExpiredDate*',
'bonusgoods.CreateTime':'CreateTime*',
'bonusgoods.UpdateTime':'UpdateTime*',
'bonusgoods.UpdateBy':'UpdateBy*',

'bonusrulesetting.BonusRuleSettingID':'BonusRuleSettingID*',
'bonusrulesetting.CompanyID':'CompanyID*',
'bonusrulesetting.BounsBase':'BounsBase*',
'bonusrulesetting.BonusValuex100':'BonusValuex100*',
'bonusrulesetting.BonusFee':'BonusFee*',
'bonusrulesetting.UpdateTime':'UpdateTime*',
'bonusrulesetting.UpdateBy':'UpdateBy*',

'bonustx.BonusTxID':'BonusTxID*',
'bonustx.CompanyID':'CompanyID*',
'bonustx.UserID':'UserID*',
'bonustx.BonusPoints':'BonusPoints*',
'bonustx.BonusTxType':'BonusTxType*',
'bonustx.BonusTxTime':'BonusTxTime*',
'bonustx.DeviceID':'DeviceID*',
'bonustx.BonusTxNote':'BonusTxNote*',

'caimaassigment.CaimaAssigmentID':'CaimaAssigmentID*',
'caimaassigment.CaimaRepositoryID':'CaimaRepositoryID*',
'caimaassigment.CompanyID':'CompanyID*',

'caimabatch.BatchID':'BatchID*',
'caimabatch.BatchName':'BatchName*',
'caimabatch.BatchDescription':'BatchDescription',

'caimarepository.caimarepositoryID':'caimarepositoryID*',
'caimarepository.CaimaID':'CaimaID*',
'caimarepository.BatchID':'BatchID*',
'caimarepository.UsageState':'UsageState*',
'caimarepository.CompanyCaima90URL':'CompanyCaima90URL*',
'caimarepository.CompanyCaima450URL':'CompanyCaima450URL*',

'company.CompanyID':'CompanyID*',
'company.CompanyAdm':'CompanyAdm*',
'company.CompanyName':'CompanyName*',
'company.CompanyDesc':'CompanyDesc*',
'company.CompanyPic':'CompanyPic',
'company.CompanyPic2':'CompanyPic2',
'company.CompanyPic3':'CompanyPic3',
'company.CompanyPic4':'CompanyPic4',
'company.CompanyPic5':'CompanyPic5',
'company.CompanyOfficialSite':'CompanyOfficialSite',
'company.ContactPerson':'ContactPerson',
'company.ContactEmail':'ContactEmail',
'company.ContactPhone':'ContactPhone',
'company.Address':'Address*',
'company.BizRegNo':'BizRegNo',
'company.parkingLot':'parkingLot',
'company.lowestSpending':'lowestSpending',
'company.StartingTime':'StartingTime',
'company.EndingTime':'EndingTime',
'company.Latitude':'Latitude*',
'company.Longitude':'Longitude*',
'company.CreateTime':'CreateTime*',
'company.UpdateTime':'UpdateTime*',
'company.CreateBy':'CreateBy*',
'company.UpdateBy':'UpdateBy*',

'companyads.CompanyAdsID':'CompanyAdsID*',
'companyads.CompanyID':'CompanyID*',
'companyads.AdsTitle':'AdsTitle*',
'companyads.AdsDesc':'AdsDesc*',
'companyads.AdsPic':'AdsPic',
'companyads.AdsCreateTime':'AdsCreateTime',
'companyads.AdsUpdateTime':'AdsUpdateTime',
'companyads.AdsUpdateBy':'AdsUpdateBy',

'companycontent.companycontentID':'companycontentID*',
'companycontent.CompanyID':'CompanyID*',
'companycontent.LanguageID':'LanguageID*',
'companycontent.CompanyName':'CompanyName',
'companycontent.CompanyDesc':'CompanyDesc',
'companycontent.Address':'Address',
'companycontent.Modified':'Modified',

'companynews.CompanyNewsID':'CompanyNewsID*',
'companynews.CompanyID':'CompanyID*',
'companynews.NewsTitle':'NewsTitle*',
'companynews.NewsDesc':'NewsDesc*',
'companynews.NewsPic':'NewsPic',
'companynews.NewsDesc2':'NewsDesc2',
'companynews.NewsPic2':'NewsPic2',
'companynews.NewsCreateTime':'NewsCreateTime',
'companynews.NewsUpdateTime':'NewsUpdateTime',
'companynews.NewsUpdateBy':'NewsUpdateBy',

'companytags.CompanyTagsID':'CompanyTagsID*',
'companytags.CompanyID':'CompanyID*',
'companytags.TagLists':'TagLists*',
'companytags.ParentTagID':'ParentTagID',

'companytemp.CompanyID':'CompanyID*',
'companytemp.CompanyAdm':'CompanyAdm*',
'companytemp.CompanyName':'CompanyName*',
'companytemp.CompanyDesc':'CompanyDesc*',
'companytemp.CompanyPic':'CompanyPic',
'companytemp.CompanyOfficialSite':'CompanyOfficialSite',
'companytemp.ContactPerson':'ContactPerson',
'companytemp.ContactEmail':'ContactEmail',
'companytemp.ContactPhone':'ContactPhone',
'companytemp.Address':'Address*',
'companytemp.BizRegNo':'BizRegNo',
'companytemp.Latitude':'Latitude',
'companytemp.Longitude':'Longitude',
'companytemp.CreateTime':'CreateTime*',
'companytemp.UpdateTime':'UpdateTime*',
'companytemp.CreateBy':'CreateBy*',
'companytemp.UpdateBy':'UpdateBy*',

'customercaima.CustomerCaimatID':'CustomerCaimatID*',
'customercaima.CaimaRepositoryID':'CaimaRepositoryID*',
'customercaima.UserID':'UserID*',

'customervehicle.CustomerVehicleID':'CustomerVehicleID*',
'customervehicle.UserID':'UserID*',
'customervehicle.CardID':'CardID*',
'customervehicle.Phone':'Phone*',

'fanscompany.promocompanyID':'promocompanyID*',
'fanscompany.PromoID':'PromoID*',
'fanscompany.CompanyID':'CompanyID*',

'goodstx.GoodsTxID':'GoodsTxID*',
'goodstx.GoodsID':'GoodsID*',
'goodstx.UserID':'UserID*',
'goodstx.GoodsTxState':'GoodsTxState*',
'goodstx.ReserveTime':'ReserveTime*',
'goodstx.RedeemTime':'RedeemTime*',

'goodstxnotes.GoodsTxID':'GoodsTxID*',
'goodstxnotes.Description':'Description*',
'goodstxnotes.CreateTime':'CreateTime*',
'goodstxnotes.UpdateTime':'UpdateTime*',
'goodstxnotes.UpdateBy':'UpdateBy*',

'group.GroupID':'GroupID*',
'group.CaimaID':'CaimaID*',
'group.GroupTypeID':'GroupTypeID*',
'group.PromoID':'PromoID*',
'group.StarterID':'StarterID*',
'group.GroupName':'GroupName*',
'group.GroupDesc':'GroupDesc',
'group.StartTime':'StartTime',
'group.DescUpdateTime':'DescUpdateTime',
'group.GroupURL':'GroupURL',

'grouptype.GroupTypeID':'GroupTypeID*',
'grouptype.PromoID':'PromoID*',
'grouptype.GroupTypeName':'GroupTypeName*',
'grouptype.GroupTypeQuote':'GroupTypeQuote',

'joinfans.JoinID':'JoinID*',
'joinfans.PromoID':'PromoID*',
'joinfans.UserID':'UserID*',
'joinfans.CompanyID':'CompanyID*',
'joinfans.Comment':'Comment',
'joinfans.JoinTime':'JoinTime',
'joinfans.LeaveTime':'LeaveTime',

'joingroup.JoinID':'JoinID*',
'joingroup.PromoID':'PromoID*',
'joingroup.UserID':'UserID*',
'joingroup.GroupID':'GroupID*',
'joingroup.Comment':'Comment',
'joingroup.JoinTime':'JoinTime',
'joingroup.LeaveTime':'LeaveTime',

'languagemapping.LanguageID':'LanguageID*',
'languagemapping.LanguageName':'LanguageName*',
'languagemapping.languageEncode':'languageEncode',

'offday.offDayID':'offDayID*',
'offday.name':'name*',

'offdaycompany.offDayCompany':'offDayCompany*',
'offdaycompany.CompanyID':'CompanyID*',
'offdaycompany.offDayID':'offDayID*',

'paymentmethod.paymentMethodID':'paymentMethodID*',
'paymentmethod.methodName':'methodName*',

'pos.PosID':'PosID*',
'pos.PosName':'PosName*',
'pos.Description':'Description',
'pos.PosState':'PosState*',
'pos.CreateTime':'CreateTime*',
'pos.UpdateTime':'UpdateTime*',
'pos.UpdateBy':'UpdateBy*',

'posnotes.PosNotesID':'PosNotesID*',
'posnotes.PosID':'PosID*',
'posnotes.Description':'Description*',
'posnotes.CreateTime':'CreateTime',
'posnotes.UpdateTime':'UpdateTime',
'posnotes.UpdateBy':'UpdateBy*',

'prizeitem.PrizeID':'PrizeID*',
'prizeitem.PromoID':'PromoID*',
'prizeitem.UpdateBy':'UpdateBy*',
'prizeitem.PrizeName':'PrizeName*',
'prizeitem.PrizeDesc':'PrizeDesc',
'prizeitem.PrizeQuantity':'PrizeQuantity*',
'prizeitem.AwardMsg':'AwardMsg',
'prizeitem.RedeemMsg':'RedeemMsg',
'prizeitem.ExpiredDate':'ExpiredDate*',
'prizeitem.ExpiredMsg':'ExpiredMsg',
'prizeitem.CreateTime':'CreateTime*',
'prizeitem.UpdateTime':'UpdateTime*',

'promotion.PromoID':'PromoID*',
'promotion.CompanyID':'CompanyID*',
'promotion.PromoAdmin':'PromoAdmin*',
'promotion.PromoName':'PromoName',
'promotion.PromoDesc':'PromoDesc',
'promotion.PromoURL':'PromoURL',
'promotion.AndroidURL':'AndroidURL',
'promotion.AppleURL':'AppleURL',
'promotion.StartTime':'StartTime*',
'promotion.EndTime':'EndTime*',
'promotion.BatchID':'BatchID*',

'rebaterulesetting.RebateRuleSettingID':'RebateRuleSettingID*',
'rebaterulesetting.CompanyID':'CompanyID*',
'rebaterulesetting.RebateBase':'RebateBase*',
'rebaterulesetting.RebateValuex100':'RebateValuex100*',
'rebaterulesetting.RebateFee':'RebateFee*',
'rebaterulesetting.UpdateTime':'UpdateTime*',
'rebaterulesetting.UpdateBy':'UpdateBy*',

'rebatestorelists.RebateStoreListsID':'RebateStoreListsID*',
'rebatestorelists.CompanyID':'CompanyID*',
'rebatestorelists.PosID':'PosID*',
'rebatestorelists.CreateTime':'CreateTime*',
'rebatestorelists.UpdateTime':'UpdateTime*',
'rebatestorelists.UpdateBy':'UpdateBy*',

'rebatetx.RebateTxID':'RebateTxID*',
'rebatetx.CompanyID':'CompanyID*',
'rebatetx.PosID':'PosID*',
'rebatetx.UserID':'UserID*',
'rebatetx.RebatePoints':'RebatePoints*',
'rebatetx.RebateTxType':'RebateTxType*',
'rebatetx.RebateTxTime':'RebateTxTime*',
'rebatetx.RebateTxNote':'RebateTxNote*',

'redeemcounter.CounterID':'CounterID*',
'redeemcounter.PromoID':'PromoID*',
'redeemcounter.CounterName':'CounterName*',
'redeemcounter.CountLocation':'CountLocation*',
'redeemcounter.AuthCode':'AuthCode*',

'staff.StaffID':'StaffID*',
'staff.Username':'名字*',
'staff.Valid':'有效*',
'staff.Password':'密碼*',
'staff.GoogleID':'GoogleID*',
'staff.UserLevel':'等級*',
'staff.StaffDesc':'說明',
'staff.Email':'Email*',
'staff.Phone':'Phone',
'staff.CreateTime':'CreateTime',
'staff.UpdateTime':'UpdateTime',
'staff.UpdateBy':'UpdateBy',

'stafflevel.UserLevel':'UserLevel*',
'stafflevel.LevelName':'LevelName*',

'storegroup.StoreGroupID':'StoreGroupID*',
'storegroup.GroupLead':'GroupLead*',
'storegroup.StoreGroupName':'StoreGroupName*',
'storegroup.SotreGroupDesc':'SotreGroupDesc',
'storegroup.StoreGroupURL':'StoreGroupURL',
'storegroup.StoreGroupState':'StoreGroupState',

'storegrouplists.StoreGroupListID':'StoreGroupListID*',
'storegrouplists.CompanyID':'CompanyID*',
'storegrouplists.StoreGroupID':'StoreGroupID*',
'storegrouplists.AllianceUserID':'AllianceUserID*',
'storegrouplists.CreateTime':'CreateTime*',
'storegrouplists.UpdateTime':'UpdateTime*',
'storegrouplists.UpdateBy':'UpdateBy*',

'tagmapping.TagID':'TagID*',
'tagmapping.ParentTagID':'ParentTagID',
'tagmapping.TagName':'TagName*',
'tagmapping.LanguageID':'LanguageID',

'user.UserID':'UserID*',
'user.UserName':'UserName*',
'user.FB_ID':'FB_ID',
'user.FB_profile':'FB_profile',
'user.RegTime':'RegTime',
'user.RegPromo':'RegPromo*',
'user.Valid':'Valid',
'user.LanguageID':'LanguageID*',

'uservehicle.UserVehicleID':'UserVehicleID*',
'uservehicle.UserID':'UserID*',
'uservehicle.CardID':'CardID',
'uservehicle.Phone':'Phone*',
}